/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.io.*;
import java.net.*;
import java.util.logging.*;
import Entity.*;
/**
 *
 * @author ASUS
 */
public class BilletForm extends java.awt.Frame {
    int xMouseB;
    int yMouseB;
    
    String user;
    Socket sock;
    ObjectOutputStream output;
    ObjectInputStream input;
    String message = "";
    String idTable;
    String nomCaisse;
    /**
     * Creates new form BilletForm1
     */
//    public BilletForm() {
//        initComponents();
//        idTable = "1";
//        nomCaisse = "1";
//        initComponents();
//        connect();
//    }
    
    public BilletForm(String id, String nomCai){
        idTable = id;
        nomCaisse = nomCai;
        initComponents();
        connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BilletScroll = new javax.swing.JScrollPane();
        Billet = new javax.swing.JTable();
        AnnulerBillet = new javax.swing.JLabel();
        Imprimer = new javax.swing.JLabel();
        Changement = new javax.swing.JTextArea();
        MontantTotal = new javax.swing.JTextArea();
        Total = new javax.swing.JTextArea();
        NomdeCaisse = new javax.swing.JTextArea();
        IDBillet = new javax.swing.JTextArea();
        Date = new javax.swing.JTextArea();
        TableBillet = new javax.swing.JTextArea();
        BilletBG = new javax.swing.JLabel();

        setFocusableWindowState(false);
        setMinimumSize(new java.awt.Dimension(652, 652));
        setUndecorated(true);
        setSize(new java.awt.Dimension(652, 652));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BilletScroll.setBorder(null);

        Billet.setFont(new java.awt.Font("Maiandra GD", 0, 12)); // NOI18N
        Billet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Billet.getTableHeader().setReorderingAllowed(false);
        BilletScroll.setViewportView(Billet);

        add(BilletScroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 54, 334, 385));

        AnnulerBillet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AnnulerBilletMouseClicked(evt);
            }
        });
        add(AnnulerBillet, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 478, 130, 26));
        add(Imprimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 478, 129, 26));

        Changement.setColumns(20);
        Changement.setFont(new java.awt.Font("Maiandra GD", 0, 12)); // NOI18N
        Changement.setRows(5);
        Changement.setBorder(null);
        add(Changement, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 428, 121, 20));

        MontantTotal.setColumns(20);
        MontantTotal.setFont(new java.awt.Font("Maiandra GD", 0, 12)); // NOI18N
        MontantTotal.setRows(5);
        MontantTotal.setBorder(null);
        add(MontantTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 340, 121, 20));

        Total.setColumns(20);
        Total.setFont(new java.awt.Font("Maiandra GD", 0, 12)); // NOI18N
        Total.setRows(5);
        Total.setBorder(null);
        add(Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 270, 121, 20));

        NomdeCaisse.setColumns(20);
        NomdeCaisse.setFont(new java.awt.Font("Maiandra GD", 0, 12)); // NOI18N
        NomdeCaisse.setRows(5);
        NomdeCaisse.setBorder(null);
        add(NomdeCaisse, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 199, 134, 20));

        IDBillet.setColumns(20);
        IDBillet.setFont(new java.awt.Font("Maiandra GD", 0, 12)); // NOI18N
        IDBillet.setRows(5);
        IDBillet.setBorder(null);
        add(IDBillet, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 125, 120, 20));

        Date.setColumns(20);
        Date.setFont(new java.awt.Font("Maiandra GD", 0, 12)); // NOI18N
        Date.setRows(5);
        Date.setBorder(null);
        add(Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 88, 120, 20));

        TableBillet.setColumns(20);
        TableBillet.setFont(new java.awt.Font("Maiandra GD", 0, 12)); // NOI18N
        TableBillet.setRows(5);
        TableBillet.setBorder(null);
        add(TableBillet, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 34, 18));

        BilletBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Billet.png"))); // NOI18N
        BilletBG.setAlignmentY(0.0F);
        BilletBG.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BilletBGMouseDragged(evt);
            }
        });
        BilletBG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BilletBGMousePressed(evt);
            }
        });
        add(BilletBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 652, 652));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void AnnulerBilletMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AnnulerBilletMouseClicked
       this.setVisible(false);
    }//GEN-LAST:event_AnnulerBilletMouseClicked

    private void BilletBGMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BilletBGMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xMouseB, y - yMouseB);
    }//GEN-LAST:event_BilletBGMouseDragged

    private void BilletBGMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BilletBGMousePressed
        xMouseB = evt.getX();
        yMouseB = evt.getY();
    }//GEN-LAST:event_BilletBGMousePressed

    //----------------------PROGESS POUR AFFICHE DES INFOS------------
   
    Thread total = new Thread(){
        public void run(){
            
            while(MontantTotal.getText() != null){
                double m;
                m = Double.parseDouble(MontantTotal.getText()) - Double.parseDouble(Total.getText());
                Changement.setText(Double.toString(m));
            }
        }
    };
    
    public void sendBillet(){
        try{
                output.writeObject("DE BILLET FORM A ADMIN - AFFICHE BILLET");
                output.flush();
                output.writeObject(idTable);
        }catch(Exception e){
            afficheErreur();
        }
    }
    
    public void afficheBillet(Billet item){
         
        TableBillet.setText(item.getIdTable());
        Date.setText(item.getDateTime());
        IDBillet.setText(item.getIdBillet());
        Total.setText(Double.toString(item.getPrixTotal()));
        NomdeCaisse.setText(nomCaisse);
    }
    
    
    
    //----------------------AFFICHE ERREUR DIALOG------------------
    public void afficheErreur(){
        Erreur404 e = new Erreur404();
        e.setVisible(true);
        e.setLocationRelativeTo(null);
    }
    
    
   //------------------INSTALLER CONNEXION A ADMIN-------------------------
    
    public class IncomingReader implements Runnable{

        @Override
        public void run() {
                try{  
                    message = (String) input.readObject();
                    System.out.println("Billet Form "  + message);
                        if(message.equals("DE SERVER A BILLET FORM - AFFICHE BILLET")){
                            Billet item = new Billet();
                            item = (Billet) input.readObject();
                            afficheBillet(item);
                            System.out.println("Billet Form" + item.getIdBillet());
                        }
                } catch (IOException ex) {
                    afficheErreur();

                } catch (ClassNotFoundException ex) {
                    afficheErreur();
                }
                
           
        }
        
    }
    
        public void closeConnexion(){
            try{
                input.close();
                output.close();
                sock.close();
            } catch (Exception e){
                
            }
        }

        public void ListenChat(){
            Thread Incoming = new Thread(new IncomingReader());
            Incoming.start();
        }

        public void connect(){
            try{
                sock = new Socket("localhost", 8064);
                output = new ObjectOutputStream(sock.getOutputStream());
                output.flush();
                input = new ObjectInputStream(sock.getInputStream());
                output.writeObject("TABLE PAYER \n");
                output.flush();
                
                sendBillet();

                ListenChat();

            }
            catch(Exception e){
                afficheErreur();
            }
        }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AnnulerBillet;
    private javax.swing.JTable Billet;
    private javax.swing.JLabel BilletBG;
    private javax.swing.JScrollPane BilletScroll;
    private javax.swing.JTextArea Changement;
    private javax.swing.JTextArea Date;
    private javax.swing.JTextArea IDBillet;
    private javax.swing.JLabel Imprimer;
    private javax.swing.JTextArea MontantTotal;
    private javax.swing.JTextArea NomdeCaisse;
    private javax.swing.JTextArea TableBillet;
    private javax.swing.JTextArea Total;
    // End of variables declaration//GEN-END:variables
}
