/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Entity.*;
import java.io.*;
import java.net.*;
import java.util.*;
import java.util.logging.*;

/**
 *
 * @author ASUS
 */
public class Caisse extends java.awt.Frame {
    int xMouseC;
    int yMouseC;
    
    String user;
    Socket sock;
    ObjectOutputStream output;
    ObjectInputStream input;
    String message = "";
    Personnel per = new Personnel();
    
    /**
     * Creates new form Caisse
     */
    public Caisse() {
        initComponents();
    }
    
    public Caisse(Personnel p){
        per = p;
        initComponents();
        connect();

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NotiScroll = new javax.swing.JScrollPane();
        chatBox = new javax.swing.JTextArea();
        Table9 = new javax.swing.JLabel();
        Table8 = new javax.swing.JLabel();
        Table7 = new javax.swing.JLabel();
        Table6 = new javax.swing.JLabel();
        Table5 = new javax.swing.JLabel();
        Table4 = new javax.swing.JLabel();
        Table3 = new javax.swing.JLabel();
        Table2 = new javax.swing.JLabel();
        Table1 = new javax.swing.JLabel();
        CaisseBG = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(652, 652));
        setUndecorated(true);
        setSize(new java.awt.Dimension(652, 652));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chatBox.setColumns(20);
        chatBox.setRows(5);
        NotiScroll.setViewportView(chatBox);

        add(NotiScroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 539, 252, 74));

        Table9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table9MouseClicked(evt);
            }
        });
        add(Table9, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 370, 172, 122));

        Table8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table8MouseClicked(evt);
            }
        });
        add(Table8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 170, 120));

        Table7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table7MouseClicked(evt);
            }
        });
        add(Table7, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 370, 172, 120));

        Table6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table6MouseClicked(evt);
            }
        });
        add(Table6, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 220, 170, 120));

        Table5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table5MouseClicked(evt);
            }
        });
        add(Table5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 218, 172, 122));

        Table4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table4MouseClicked(evt);
            }
        });
        add(Table4, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 220, 170, 120));

        Table3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table3MouseClicked(evt);
            }
        });
        add(Table3, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 70, 170, 120));

        Table2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table2MouseClicked(evt);
            }
        });
        add(Table2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 170, 120));

        Table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table1MouseClicked(evt);
            }
        });
        add(Table1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 70, 172, 122));

        CaisseBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Caisse.png"))); // NOI18N
        CaisseBG.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                CaisseBGMouseDragged(evt);
            }
        });
        CaisseBG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CaisseBGMousePressed(evt);
            }
        });
        add(CaisseBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 652, 652));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void Table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table1MouseClicked
        String idTab = "tab001";
        BilletForm b = new BilletForm(idTab, per.getNomPersonnel());
        b.setVisible(true);
        b.setLocationRelativeTo(null);
    }//GEN-LAST:event_Table1MouseClicked

    private void Table2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table2MouseClicked
        String idTab = "tab002";
        BilletForm b = new BilletForm(idTab, per.getNomPersonnel()); 
        b.setVisible(true);
        b.setLocationRelativeTo(null);
    }//GEN-LAST:event_Table2MouseClicked

    private void Table3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table3MouseClicked
        String idTab = "tab003";
        BilletForm b = new BilletForm(idTab, per.getNomPersonnel());
        b.setVisible(true);
        b.setLocationRelativeTo(null);
    }//GEN-LAST:event_Table3MouseClicked

    private void Table4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table4MouseClicked
        String idTab = "tab004";
        BilletForm b = new BilletForm(idTab, per.getNomPersonnel());
        b.setVisible(true);
        b.setLocationRelativeTo(null);
    }//GEN-LAST:event_Table4MouseClicked

    private void Table5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table5MouseClicked
        String idTab = "tab005";
        BilletForm b = new BilletForm(idTab, per.getNomPersonnel());
        b.setVisible(true);
        b.setLocationRelativeTo(null);
    }//GEN-LAST:event_Table5MouseClicked

    private void Table6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table6MouseClicked
        String idTab = "tab006";
        BilletForm b = new BilletForm(idTab, per.getNomPersonnel());
        b.setVisible(true);
        b.setLocationRelativeTo(null);
    }//GEN-LAST:event_Table6MouseClicked

    private void Table7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table7MouseClicked
        String idTab = "tab007";
        BilletForm b = new BilletForm(idTab, per.getNomPersonnel());
        b.setVisible(true);
        b.setLocationRelativeTo(null);
    }//GEN-LAST:event_Table7MouseClicked

    private void Table8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table8MouseClicked
        String idTab = "tab008";
        BilletForm b = new BilletForm(idTab, per.getNomPersonnel());
        b.setVisible(true);
        b.setLocationRelativeTo(null);
    }//GEN-LAST:event_Table8MouseClicked

    private void Table9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table9MouseClicked
        String idTab = "tab009";
        BilletForm b = new BilletForm(idTab, per.getNomPersonnel());
        b.setVisible(true);
        b.setLocationRelativeTo(null);
    }//GEN-LAST:event_Table9MouseClicked

    private void CaisseBGMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CaisseBGMousePressed
        xMouseC = evt.getX();
        yMouseC = evt.getY();
    }//GEN-LAST:event_CaisseBGMousePressed

    private void CaisseBGMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CaisseBGMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xMouseC, y - yMouseC);
    }//GEN-LAST:event_CaisseBGMouseDragged

    
    
    
    
    
    
    
    
    
    //------------------INSTALLER CONNEXION A ADMIN-------------------------
    
    public class IncomingReader implements Runnable{

        @Override
        public void run() {
            
                try{  
                    
                    message = (String) input.readObject();
                    do{
                    
                    if (message.equals("FROM SERVER")){
                        chatBox.append(message + "\n");

                        message = (String) input.readObject();
                        if(message != null){
                        chatBox.append(message + "\n");}
                    }
                    }while(!message.equals("SERVER - NULL"));

                } catch (IOException ex) {
                    chatBox.append("Connexion erreur... \n");

                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(ChefCuisine.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            
        }
        
    }
    
    
        public void closeConnexion(){
            try{
                output.writeObject("END CONNEXION DE PER");
                output.flush();
                input.close();
                output.close();
                sock.close();
            } catch (Exception e){
                chatBox.append("Desactive erreur.... \n");
            }
        }

        public void ListenChat(){
            Thread Incoming = new Thread(new IncomingReader());
            Incoming.start();
        }

        public void connect(){
            try{
                sock = new Socket("localhost", 8064);
                output = new ObjectOutputStream(sock.getOutputStream());
                output.flush();
                input = new ObjectInputStream(sock.getInputStream());
                output.writeObject("CAISSE CONNECT \n");
                output.flush();
                message = (String) input.readObject();
                chatBox.append(message + "\n");

                ListenChat();

            }
            catch(Exception e){
                chatBox.append("Can not connect to server.... \n");
            }
        }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       Caisse caisse = new Caisse();
       caisse.setVisible(true);
       caisse.setLocationRelativeTo(null);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CaisseBG;
    private javax.swing.JScrollPane NotiScroll;
    private javax.swing.JLabel Table1;
    private javax.swing.JLabel Table2;
    private javax.swing.JLabel Table3;
    private javax.swing.JLabel Table4;
    private javax.swing.JLabel Table5;
    private javax.swing.JLabel Table6;
    private javax.swing.JLabel Table7;
    private javax.swing.JLabel Table8;
    private javax.swing.JLabel Table9;
    private javax.swing.JTextArea chatBox;
    // End of variables declaration//GEN-END:variables
}
